BUGFIX: options for haproxy command are required elements
It fixes following exception:
sudo haproxytool haproxy -D /var/run/hapee
Traceback (most recent call last):
  File "/opt/blue-python/3.4/bin/haproxytool", line 10, in <module>
    sys.exit(main())
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxytool/cli.py", line 48, in main
    call_main(module_object)
  File "/opt/blue-python/3.4/lib/python3.4/site-packages/haproxytool/haproxy.py", line 161, in main
    getattr(cmd, method)()
TypeError: getattr(): attribute name must be string